### ISSUE TITLE
wooyun wifi默认密码是多少？

### ISSUE THREAD

**Issue by gitfuzzing** [lxj616/wooyunwifi_ofdoom#1]
试了wooyunwifi也不对啊

**Comment by lxj616** [comment]
老版本没有默认密码，需要先在luci里面设置，新版本密码为wooyunwifi，请用有线方式连接配置（不然配置中无线会断开），如果遇到问题请直接捅后面reset 8秒钟重置

此非wooyunwifi的repository，但我会尽力回答，详细解答需要等wooyun回归后才能继续（我现在也没wooyunwifi了）
